sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t eshuster/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true eshuster/react-test npm test

after_success:
    - docker build -t eshuster/multi-client ./client
    - docker build -t eshuster/multi-server ./server
    - docker build -t eshuster/multi-nginx ./nginx
    - docker build -t eshuster/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push eshuster/multi-client
    - docker push eshuster/multi-server
    - docker push eshuster/multi-nginx
    - docker push eshuster/multi-worker


deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-496947949261
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY